/*
 * Copyright Notice ====================================================
 * This file contains proprietary information of Hewlett-Packard Co.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2012 All rights reserved. =============================
 */

package chapterOne;

import java.util.ArrayList;
import java.util.List;

public class LowCodeTest
{
    public static void main(String[] args)
    {
        String[] str = {"ProScAM", "ProScAR", "ProScASS", "ProScBQA", "ProScBTA", "ProScBTB", "ProScBTQA", "ProScCCA",
                "ProScCPA1000", "ProScCPA200", "ProScCPA50", "ProScCSTD", "ProScDSH", "ProScEFI", "ProScGHPUX", "ProScGLINUX",
                "ProScHAE", "ProScHC", "ProScHHA", "ProScICA", "ProScIIA", "ProScIQA", "ProScISH", "ProScLD", "ProScLM",
                "ProScNAR", "ProScPA", "ProScPAS", "ProScPatch", "ProScPNN", "ProScPR", "ProScPRU", "ProScQA", "ProScRA",
                "ProScRS", "ProScSA", "ProScSF", "ProScSH", "ProScTOS", "ProScTVM", "PS1CCA10OFF", "PS3PARAOPOFF", "PS3PARAOPSTD",
                "PS3PARHCOFF", "PS3PARHCSTD", "PS3PARPAOFF", "PS3PARPASTD", "PS3PARRbOFF", "PS3PARRbSTD", "PS3PARSASOFF",
                "PS3PARSASSTD", "PSAAVEOFF", "PSAAVESTD", "PSBCS100OFF", "PSBCS100STD", "PSBCS10STD", "PSBCS11OFF", "PSBCS25STD",
                "PSBCS26OFF", "PSBCS50OFF", "PSBCS50STD", "PSBFWGapOFF", "PSBFWGapSTD", "PSBFWUROFF", "PSBFWURSTD",
                "PSBHCAddlOFF", "PSBHCAddlSTD", "PSBIAHCOFF", "PSBIAHCSTD", "PSBnchmkOFF", "PSBnchmkSTD", "PSBSAEDSTD",
                "PSBSCImOFF", "PSBSCImSTD", "PSBSFEDSTD", "PSBSFUAEOFF", "PSBSFUAESTD", "PSBSFUEAOFF", "PSBSFUEASTD",
                "PSBSFUFEOFF", "PSBSFUFESTD", "PSBSHCSOFF", "PSBSHCSSTD", "PSBSICEDSTD", "PSBSMEKIOFF", "PSBSMEKISTD",
                "PSBSMFUAEOFF", "PSBSMFUAESTD", "PSBSMFUFEOFF", "PSBSMFUFESTD", "PSBSMUDHWOFF", "PSBSMUDHWSTD", "PSBSMUSHWOFF",
                "PSBSMUSHWSTD", "PSBSVTIEDSTD", "PSBTBOFF", "PSBTBSTD", "PSBTTAOFF", "PSBTTASTD", "PSBWAHCOFF", "PSBWAHCSTD",
                "PSCcKPIOFF", "PSCcKPISTD", "PSCCSAddOFF", "PSCCSAddSTD", "PSCCSOFF", "PSCCSSTD", "PSCDAdjst", "PSCIGSOFF",
                "PSCIGSSTD", "PSCODEL", "PSCSAOFF", "PSCSASTD", "PSCSBASOFF", "PSCSBASSTD", "PSCSMEASOFF", "PSCSMEASSTD",
                "PSCstmASMOFF", "PSCstmASMSTD", "PSCstmTCOFF", "PSCstmTCSTD", "PSCTA25kOFF", "PSCTA25kSTD", "PSCTAOFF",
                "PSCTAssLGOFF", "PSCTAssLGSTD", "PSCTAssSMOFF", "PSCTAssSMSTD", "PSCTASTD", "PSCVScrptOFF", "PSCVScrptSTD",
                "PSCVUpgAOFF", "PSCVUpgASTD", "PSDMMnfExOFF", "PSDMMnfExSTD", "PSDMMnfOFF", "PSDMMnfSTD", "PSDMOpSExOFF",
                "PSDMOpSExSTD", "PSDMOpSOFF", "PSDMOpSSTD", "PSDMSCExOFF", "PSDMSCExSTD", "PSDMVMEDSTD", "PSDPPABOFF",
                "PSDPPABSTD", "PSDPPAEOFF", "PSDPPAESTD", "PSDPROFF", "PSDPRSTD", "PSDSIPOFF", "PSDSIPSTD", "PSDSntzHsOFF",
                "PSDSntzHsSTD", "PSDSntzOFF", "PSDSntzSTD", "PSDSntzVlOFF", "PSDSntzVlSTD", "PSDSSIPOFF", "PSDSSIPSTD",
                "PSEdCrdOFF", "PSEdCrdSTD", "PSEDSAssOFF", "PSEDSAssSTD", "PSEEA100kOFF", "PSEEA100kSTD", "PSEEA100OFF",
                "PSEEA100STD", "PSEEA10kOFF", "PSEEA10kSTD", "PSEEA10OFF", "PSEEA10STD", "PSEEA25kOFF", "PSEEA25kSTD",
                "PSEEA25OFF", "PSEEA25STD", "PSEEA50kOFF", "PSEEA50kSTD", "PSEEA50OFF", "PSEEA50STD", "PSEPAOFF", "PSEPASTD",
                "PSERVEOFF", "PSERVESTD", "PSESDMWBOFF", "PSESDMWBSTD", "PSESDMWEOFF", "PSESDMWESTD", "PSEVADIOFF", "PSEVADISTD",
                "PSEVAFw2STD", "PSEVAFw3OFF", "PSEVAFw5STD", "PSEVAFw6OFF", "PSEVAFWUpOFF", "PSEVAFWUpSTD", "PSEVAHCOFF",
                "PSEVAHCSTD", "PSEVAPAOFF", "PSEVAPASTD", "PSEVAPMOOFF", "PSEVAPMOSTD", "PSFUECASOFF", "PSFUECASSTD",
                "PSFUMASOFF", "PSFUMASSTD", "PSFUMSFOFF", "PSFUMSFSTD", "PSFWUAOFF", "PSFWUASTD", "PSFWUIOFF", "PSFWUISTD",
                "PSFWUPaddOFF", "PSFWUPaddSTD", "PSFWUPOFF", "PSFWUPSTD", "PSHAMngtOFF", "PSHAMngtSTD", "PSHPCCMOFF",
                "PSHPCCMSTD", "PSHPNOFF", "PSHPNSTD", "PSHWSWAOFF", "PSHWSWASTD", "PSICAOFF", "PSICASTD", "PSICCA100OFF",
                "PSICCA100STD", "PSICCA10STD", "PSICCA25OFF", "PSICCA25STD", "PSICCA50OFF", "PSICCA50STD", "PSICFEDSTD",
                "PSICMHEDSTD", "PSICPTMOFF", "PSICPTMSTD", "PSICSDEDSTD", "PSICSRSAOFF", "PSICSRSASTD", "PSICVIMCBOFF",
                "PSICVIMCBSTD", "PSICVIMPVOFF", "PSICVIMPVSTD", "PSICVINPVOFF", "PSICVINPVSTD", "PSIDSWRSAOFF", "PSIDSWRSASTD",
                "PSIFOEDSTD", "PSIIAOFF", "PSIIASTD", "PSIOPROFF", "PSIOPRSTD", "PSIQAOFF", "PSIQASTD", "PSIRSAddOFF",
                "PSIRSAddSTD", "PSIRSAISOFF", "PSIRSAISSTD", "PSIRSARSAOFF", "PSIRSARSASTD", "PSIRSHOOFF", "PSIRSHOOSTD",
                "PSIRSNHOOFF", "PSIRSNHOOSTD", "PSISIMEDSTD", "PSITAOFF", "PSITASTD", "PSITMAOFF", "PSITMASTD", "PSITSMASSOFF",
                "PSITSMASSSTD", "PSIVEDSTD", "PSIVGSOFF", "PSIVGSSTD", "PSIVMWIEDSTD", "PSIWSHVEDSTD", "PSLibHCOFF", "PSLibHCSTD",
                "PSMESRSAOFF", "PSMESRSASTD", "PSMSPCOFF", "PSMSPCSTD", "PSMSSRSAOFF", "PSMSSRSASTD", "PSNARAdlOFF",
                "PSNARAdlSTD", "PSNAROFF", "PSNARSTD", "PSNASHCOFF", "PSNASHCSTD", "PSNETSWPAOFF", "PSNETSWPASTD", "PSNETSWPOFF",
                "PSNETSWPSTD", "PSNNSF50OFF", "PSNNSF50STD", "PSNNSFADDOFF", "PSNNSFADDSTD", "PSOCPEOFF", "PSOCPESTD",
                "PSODBSGOFF", "PSODBSGSTD", "PSOrDbUpOFF", "PSOrDbUpSTD", "PSOSHOFF", "PSOSHSTD", "PSOSPAADLOFF", "PSOSPAADLSTD",
                "PSOSPatchOFF", "PSOSPatchSTD", "PSOSPCOFF", "PSOSPCSTD", "PSOTASOFF", "PSOTASSTD", "PSPAHPDAOFF", "PSPAHPDASTD",
                "PSPALSSTD", "PSPASSAddOFF", "PSPASSAddSTD", "PSPCAFSTD", "PSPCAssLHOFF", "PSPCAssLHSTD", "PSPCCROFF",
                "PSPCCRSTD", "PSPCISSTD", "PSPCISTD", "PSPCSAROFF", "PSPCSARSTD", "PSPCVEOFF", "PSPCVESTD", "PSPenTstOFF",
                "PSPenTstSTD", "PSPolyHCOFF", "PSPolyHCSTD", "PSPrcImpOFF", "PSPrcImpSTD", "PSPU1SRVOFF", "PSPU1SRVSTD",
                "PSPVTROFF", "PSPVTRSTD", "PSQMADAssOFF", "PSQMADAssSTD", "PSQMEAssOFF", "PSQMEAssSTD", "PSQTAOFF", "PSQTASTD",
                "PSRIBnchOFF", "PSRIBnchSTD", "PSRSAOFF", "PSRSASTD", "PSRSPUAAOFF", "PSRSPUAASTD", "PSRSPUFAOFF", "PSRSPUFASTD",
                "PSSANASOFF", "PSSANASSTD", "PSSANFUBOFF", "PSSANFUBSTD", "PSSANFUEOFF", "PSSANFUESTD", "PSSANIQOFF",
                "PSSANIQSTD", "PSSANSAOFF", "PSSANSASTD", "PSSAPAPCOFF", "PSSAPAPCSTD", "PSSAPCapPOFF", "PSSAPCapPSTD",
                "PSSAPHCMROFF", "PSSAPHCMRSTD", "PSSAPPAOFF", "PSSAPPASTD", "PSSAPPCOFF", "PSSAPPCSTD", "PSSAPPOFF", "PSSAPPSTD",
                "PSSAPTABIOFF", "PSSAPTABISTD", "PSSAPTAOFF", "PSSAPTASTD", "PSSAPTERPOFF", "PSSAPTERPSTD", "PSSAPTSCMOFF",
                "PSSAPTSCMSTD", "PSSAROFF", "PSSARSTD", "PSSAwSOFF", "PSSAwSSTD", "PSSCAD", "PSSCAdjst", "PSSCmpAssOFF",
                "PSSCmpAssSTD", "PSSDMEVAOFF", "PSSDMEVASTD", "PSSDMOSOFF", "PSSDMOSSTD", "PSSFAOFF", "PSSFASTD", "PSSGILXOFF",
                "PSSGILXSTD", "PSSGIUXOFF", "PSSGIUXSTD", "PSSHCDrctOFF", "PSSHCDrctSTD", "PSSHCOFF", "PSSHCOnOFF", "PSSHCOnSTD",
                "PSSHCSTD", "PSSITSMAOFF", "PSSITSMSTD", "PSSLMCtlgOFF", "PSSLMCtlgSTD", "PSSMPS12OFF", "PSSMPS12STD",
                "PSSMPS4AOFF", "PSSMPS4ASTD", "PSSMSAddSTD", "PSSMSOFF", "PSSMSSTD", "PSSNSAddOFF", "PSSOBSCOFF", "PSSOBSCSTD",
                "PSSPROFF", "PSSPRSTD", "PSSPSOFF", "PSSPSSTD", "PSSQAssOFF", "PSSQAssSTD", "PSSRAOFF", "PSSRASTD", "PSSRAVOFF",
                "PSSRAVSTD", "PSSRVEOFF", "PSSRVESTD", "PSStoATOFF", "PSStoATSTD", "PSSTOCSEXOFF", "PSSTOCSEXSTD", "PSStoGEOFF",
                "PSStoGESTD", "PSStoHATAOFF", "PSStoHATASTD", "PSStoHATEOFF", "PSStoHATESTD", "PSStoSvrAOFF", "PSStoSvrASTD",
                "PSSTOTHCSOFF", "PSSTOTHCSSTD", "PSStSNFWMOFF", "PSStSNFWMSTD", "PSSTVCSOFF", "PSSTVCSSTD", "PSSvrFWRcOFF",
                "PSSvrFWRcSTD", "PSSVSPHCOFF", "PSSVSPHCSTD", "PSSVSPTOAOFF", "PSSVSPTOASTD", "PSTASAPBWOFF", "PSTASAPBWSTD",
                "PSTASAPEvOFF", "PSTASAPEvSTD", "PSTASAPJSOFF", "PSTASAPJSSTD", "PSTBWAOFF", "PSTBWASTD", "PSTOSOFF",
                "PSTOSPUBSTD", "PSTOSSTD", "PSTskExOFF", "PSTskExSTD", "PSTSMAssOFF", "PSTSMAssSTD", "PSUSIPOFF", "PSUSIPSTD",
                "PSUSSIPOFF", "PSUSSIPSTD", "PSVCEMEDSTD", "PSVCMRSAOFF", "PSVCMRSASTD", "PSVDIPCOFF", "PSVDIPCSTD", "PSVDIPSOFF",
                "PSVDIPSSTD", "PSVLHCOFF", "PSVLHCSTD", "PSVMCP200OFF", "PSVMCP200STD", "PSVMCPA50OFF", "PSVMCPA50STD",
                "PSVMHCOFF", "PSVMHCSTD", "PSVMTOOFF", "PSVMTOSTD", "PSVPAOFF", "PSVPASTD", "PSVRWCAOFF", "PSVRWCASTD",
                "PSVSVRSAOFF", "PSVSVRSASTD", "PSVulScnOFF", "PSVulScnSTD", "PSVVSICEDSTD", "PSVVSOEDSTD", "PSVVSWNEDSTD",
                "PSWAAssOFF", "PSWAAssSTD", "PSWCCSOFF", "PSWCCSSTD", "PSWebGvSOFF", "PSWebGvSSTD", "PSWinPAOFF", "PSWinPASTD",
                "PSX9kTOAOFF", "PSX9kTOASTD", "PSX9kUSBOFF", "PSX9kUSBSTD", "PSX9kUSEOFF", "PSX9kUSESTD", "PSXDSSAOFF",
                "PSXDSSASTD", "SPFUECFOFF", "SPFUECFSTD"};
        String[] str2 = {"PS1WW_STDHR", "PS2WW_STDHR", "PS4WW_STDHR", "PS5WW_STDHR", "PS7WW_STDHR", "PS8WW_STDHR", "PS10WW_STDHR",
                "PS12WW_STDHR", "PS14WW_STDHR", "PS18WW_STDHR", "PS25WW_STDHR", "PSCTAssLGSTD", "PS78WW_STDHR", "PS88WW_STDHR",
                "PS89WW_STDHR", "PS102WW_STDHR", "PS119WW_STDHR", "PS120WW_STDHR", "PS128WW_STDHR", "PS131WW_STDHR", "PSTOSSTD",
                "PS134WW_STDHR", "PS136WW_STDHR", "PS137WW_STDHR", "PS142WW_STDHR", "PS144WW_STDHR", "PS145WW_STDHR",
                "PS176WW_STDHR", "PS179WW_STDHR", "PS194WW_STDHR", "PS84WW_STDHR", "PS101WW_STDHR", "PS6WW_STDHR", "PS56WW_STDHR",
                "PS11WW_STDHR", "PS135WW_STDHR", "PS138WW_STDHR", "PS143WW_STDHR", "PS13WW_STDHR", "PS15WW_STDHR", "PS17WW_STDHR",
                "PS177WW_STDHR", "PS86WW_STDHR", "PS181WW_STDHR", "PS195WW_STDHR", "PS199WW_STDHR", "PS200WW_STDHR",
                "PS201WW_STDHR", "PS178WW_STDHR", "PSSvrFWRcSTD", "PSSHCOFF", "PSBTBOFF", "PSBTTAOFF", "PSBFWUROFF",
                "PSOSPatchOFF", "PSStoHATEOFF", "PSEVAFWUpOFF", "PSStSNFWMOFF", "PSEVAHCOFF", "PSIRSNHOOFF", "PSCTAssSMOFF",
                "PSVulScnOFF", "PSSHCOnOFF", "PSSHCDrctOFF", "PSEVAFw5STD", "PSIRSAISOFF", "PSIRSAddOFF", "PSPCAssLHOFF",
                "PSSANIQOFF", "PSFUMSFOFF", "PSFUMASOFF", "SPFUECFOFF", "PSBSMFUFEOFF", "PSBSFUFEOFF", "PSBSFUEAOFF",
                "PSBSMEKIOFF", "PSX9kUSBOFF", "PSSANFUBOFF", "PSDPROFF", "PSEVAFw2STD", "PSBFWGapOFF", "PSIQAOFF", "PSStoHATAOFF",
                "PSBSFUAEOFF", "PSFUECASOFF", "PSBSMFUAEOFF", "PSSANASOFF", "PSSANSAOFF", "PSEVADIOFF", "PSBSMUSHWOFF",
                "PSCstmASMOFF", "PSX9kTOAOFF", "PSSANFUEOFF", "PSFWUPOFF", "PSFWUPaddOFF", "PSPCVEOFF", "PSBSMUDHWOFF"};

        List<String> list = new ArrayList<String>();
        for (String fullcell : str)
        {
            boolean flag = false;
            for (String cell : str2)
            {
                if (cell.equalsIgnoreCase(fullcell))
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                list.add(fullcell);
            }
        }
        for (String pStr : list)
        {
            System.out.println(pStr);
        }
    }
}
